{{- if and .Values.transport.ingress.enabled (or (eq .Values.transport.mode "sse") (eq .Values.transport.mode "http")) }}
{{- $fullName := include "mcp-server-kubernetes.fullname" . -}}
{{- $svcPort := .Values.transport.service.port -}}
{{- if and .Values.transport.ingress.className (not (hasKey .Values.transport.ingress.annotations "kubernetes.io/ingress.class")) }}
  {{- $_ := set .Values.transport.ingress.annotations "kubernetes.io/ingress.class" .Values.transport.ingress.className}}
{{- end }}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion }}
apiVersion: networking.k8s.io/v1beta1
{{- else }}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "mcp-server-kubernetes.labels" . | nindent 4 }}
  {{- $commonAnnotations := include "mcp-server-kubernetes.annotations" . }}
  {{- if or .Values.transport.ingress.annotations $commonAnnotations }}
  annotations:
    {{- if $commonAnnotations }}
    {{- $commonAnnotations | nindent 4 }}
    {{- end }}
    {{- with .Values.transport.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if and .Values.transport.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.transport.ingress.className }}
  {{- end }}
  {{- if .Values.transport.ingress.tls }}
  tls:
    {{- range .Values.transport.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.transport.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- if and .pathType (semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion) }}
            pathType: {{ .pathType }}
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ $fullName }}
                port:
                  number: {{ $svcPort }}
              {{- else }}
              serviceName: {{ $fullName }}
              servicePort: {{ $svcPort }}
              {{- end }}
          {{- end }}
    {{- end }}
{{- end }}