{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-server-kubernetes.serviceAccountName" . }}
  labels:
    {{- include "mcp-server-kubernetes.labels" . | nindent 4 }}
  {{- $commonAnnotations := include "mcp-server-kubernetes.annotations" . }}
  {{- if or .Values.serviceAccount.annotations $commonAnnotations }}
  annotations:
    {{- if $commonAnnotations }}
    {{- $commonAnnotations | nindent 4 }}
    {{- end }}
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
{{- end }}